baseURL: 'https://just-worker.github.io'
title: just-worker
theme: hugo-theme-ladder
license: MIT
homepage: 'https://just-worker.github.io'
defaultContentLanguage: zh
languageCode: "zh-Hans"
hasCJKLanguage: true
paginate: 10
menu:
  main:
    - name: 全部文章
      url: /blog
      weight: 1
    - name: 分类管理
      url: /tags
      weight: 2
    - name: 历史记录
      url: /archives
      weight: 3  
languages:
  zh:
    menu:
      main:
        - name: 全部文章
          url: /blog
          weight: 1
        - name: 分类管理
          url: /tags
          weight: 2
        - name: 历史记录
          url: /archives
          weight: 3  
params:
  brand: 我的主页
  avatarURL: /images/avatar.jpeg
  author: just-worker
  favicon: /images/avatar.jpeg
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: false
    showMetaTags: true
  darkModeTheme: data-dark-mode
  #darkModeTheme: icy-dark-mode
  social:
    - name: GitHub
      pre: >-
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: 'https://github.com/guangzhengli/hugo-theme-ladder'
taxonomies:
  tag: tags
